---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: buzzim-admin
    app.kubernetes.io/version : '1.0.0'
    app.kubernetes.io/component: im-admin-service
    app.kubernetes.io/part-of: buzzim
  name: buzzim-admin-configmap
  namespace: buzzim-admin
data:
  PORT: "11080"
  LOG_LEVEL: "debug"
  LOG_JSON: "no"
  ENABLE_SWAGGER_UI: "yes"
  BUZZIM_ADMIN_DB_HOST: "stolon-proxy-service.default.svc.cluster.local"
  BUZZIM_ADMIN_DB_PORT: "5432"
  BUZZIM_ADMIN_DB_DATABASE: "buzzim_admin"
  BUZZIM_ADMIN_DB_USER: "buzzim_admin"
  BUZZIM_URL_PATH_PREFIX: "im"
  SYNAPSE_IMAGE: "dialogicbuzz/synapse:4.0.0.51"
  SYGNAL_IMAGE: "dialogicbuzz/sygnal:4.0.0.51"
  APNS_APP_NAME: "com.dialogic.buzz"
  APNS_CERT_TYPE: "production"
  GCM_APP_NAME: "com.dialogic.im"


